config/routes.rb
SearchFood::Application.routes.draw do

  devise_for :users

  resources :services

  resources :agencies do
    
    resources :volunteers
    
    resources :updates

    resources :clients

  end

  root 'pages#home'

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	belongs_to :agency
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]
  before_action :_load_agency_from_url
  before_action :authenticate_user!, :except => [:new, :create]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = @agency_from_url.volunteers.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = @agency_from_url.volunteers.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = @agency_from_url.volunteers.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        AgencyMailer.new_volunteer(@volunteer).deliver
        format.html { redirect_to agency_path(@volunteer.agency), notice: 'Thank you for your interest in volunteering. Our Agency supervisor will contact you soon.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to agency_path(@volunteer.agency), notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:name, :yob, :phone, :email)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= simple_form_for([@agency_from_url, @volunteer]) do |f| %>
	<div class="form_wrapper">
	  <%= f.input :name %>
	  <%= f.input :yob, :label => "Birth Year", :as => :date,
        :start_year => Time.now.year-100, :end_year => Time.now.year,
        :order => [:year] %>
	  <%= f.input :phone %>
	  <%= f.input :email %>
	 
	  <div class="actions">
	    <%= f.submit :class => "btn btn-primary" %>
	  </div>
	</div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', agency_volunteer_path(@agency_from_url, @volunteer) %> |
<%= link_to 'Back', agency_volunteers_path(@agency_from_url) %>

app/views/volunteers/index.html.erb
<h1><%= @agency_from_url.name %> Volunteers</h1>

<div class="text-right">
  <%= link_to 'New Volunteer', new_agency_volunteer_path(@agency_from_url), :class => "btn btn-primary" %>
</div>

<hr>

<table class= "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Yob</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <td><%= link_to volunteer.name, "mailto:#{volunteer.email}" %></td>
        <td><%= (Time.now.year - volunteer.yob.year) %></td>
        <td><%= volunteer.phone %></td>
        <td><%= volunteer.email %></td>
        <td><%= link_to 'Show', agency_volunteer_path(volunteer.agency, volunteer) %></td>
        <td><%= link_to 'Edit', edit_agency_volunteer_path(volunteer.agency, volunteer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', agency_volunteers_path(@agency_from_url) %>

app/views/volunteers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @volunteer.name %>
</p>

<p>
  <strong>Yob:</strong>
  <%= @volunteer.yob %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @volunteer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @volunteer.email %>
</p>

<%= link_to 'Edit', edit_agency_volunteer_path(@volunteer.agency, @volunteer) %> |
<%= link_to 'Back', agency_volunteers_path(@volunteer.agency) %>