config/routes.rb
SearchFood::Application.routes.draw do

  devise_for :users

  resources :services

  resources :agencies do
    
    resources :volunteers
    
    resources :updates

    resources :clients

  end

  root 'pages#home'

end

app/models/update.rb
class Update < ActiveRecord::Base
	belongs_to :agency
	belongs_to :user

	validates_presence_of :content
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]
  before_action :_load_agency_from_url
  before_action :authenticate_user!

  # GET /updates
  # GET /updates.json
  def index
    @updates = @agency_from_url.updates.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = @agency_from_url.updates.new
  end

  # GET /updates/1/edit
  def edit
    _ensure_user_can_edit(@update)
  end

  # POST /updates
  # POST /updates.json
  def create
    
    @update = @agency_from_url.updates.new(update_params)
    @update.user = current_user

    respond_to do |format|
      if @update.save
        format.html { redirect_to agency_path(@agency_from_url), notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    _ensure_user_can_edit(@update)
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to agency_path(@agency_from_url), notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    _ensure_user_can_edit(@update)
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:content)
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= simple_form_for([@agency_from_url, @update]) do |f| %>
	<div class="form_wrapper">
	  <%= f.error_notification %>

	  <div class="form-inputs">
	    <%= f.input :content %>
	    <div class="text-right"><span class="countdown"></span></div>
	  </div>

	  <div class="form-actions">
	    <%= f.button :submit, :class => "btn btn-primary" %>
	  </div>
	</div>
<% end %>

<script type="text/javascript">
  var updateCountdown;

  updateCountdown = function() {
    var remaining;
    remaining = 140 - jQuery("#update_content").val().length;
    jQuery(".countdown").text(remaining + "");
  };

  jQuery(document).ready(function($) {
    updateCountdown();
    $("#update_content").change(updateCountdown);
    $("#update_content").keyup(updateCountdown);
    if (jQuery("#update_content").val().length === 0) {
      jQuery(".countdown").addClass("negative");
    }
  });
</script>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', agency_update_path(@update.agency, @update) %> |
<%= link_to 'Back', agency_updates_path(@update.agency) %>

app/views/updates/index.html.erb
<h1><%= @agency_from_url.name %> Updates</h1>

<div class="text-right">
  <%= link_to 'New Update', new_agency_update_path(@agency_from_url), :class => "btn btn-primary" %>
</div>

<hr>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= truncate(update.content, :length => 100) %></td>
        <td><%= link_to 'Show', agency_update_path(update.agency, update), :class => "btn btn-sm btn-default" %></td>
        <td><%= link_to 'Edit', edit_agency_update_path(update.agency, update), :class => "btn btn-sm btn-default" %></td>
        <td><%= link_to 'Destroy', agency_update_path(update.agency, update), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-danger pull-right" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @update.content %>
</p>

<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>