config/routes.rb
SearchFood::Application.routes.draw do

  devise_for :users

  resources :services

  resources :agencies do
    
    resources :volunteers
    
    resources :updates

    resources :clients

  end

  root 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>foogler</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agency Tracker</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "cOT.jpg" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("acfb_logo.png"), root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Update", agency_updates_path(@agency_from_url) if @agency_from_url %></li>
        <li><%= link_to "Volunteers", agency_volunteers_path(@agency_from_url) if @agency_from_url %></li>
        <li><%= link_to "Clients", agency_clients_path(@agency_from_url) if @agency_from_url %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Agencies", agencies_path %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if @full_width == true %>
  <%= yield(:agency_header) %>
  <%= yield %>
<% else %>
  <div class="container">
    <% if notice %><div class="alert alert-success"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-danger"><%= alert %></div><% end %>
  	<%= yield %>
  </div>
<% end %>

<footer class="footer">
  <ul class="list-inline">
    <li><iframe src="http://ghbtns.com/github-btn.html?user=morganjlopes&repo=search_food&type=fork&size=large" height="30" width="100" frameborder="0" scrolling="0" style="width:100px; height: 30px;" allowTransparency="true"></iframe></li>
    <li><iframe src="http://ghbtns.com/github-btn.html?user=moragnjlopes&repo=search_food&type=watch&size=large" height="30" width="100" frameborder="0" scrolling="0" style="width:100px; height: 30px;" allowTransparency="true"></iframe></li>
  </ul>
</footer>

</body>
</html>